$('.owl-carousel').owlCarousel({
    loop:true,
    margin:12,
    nav:false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        800:{
            items:4
        },
        1500:{
            items:7
        }
    }
})